data_covid = 'https://www.datos.gov.co/api/views/gt2j-8ykr/rows.csv?accessType=DOWNLOAD'
data_covid_uci_bogota = 'https://datosabiertos.bogota.gov.co/dataset/adebac34-7974-4aa8-a31d-97b2b6796e4b/resource/6657cbbc-8277-4caf-8823-3350f253ae64/download/3.osb_ocupacion_ucis_covid-19_22022021.csv'
out_name_s3_data_covid_uci_bogota='data_covid_uci_bogota'
output_data_covid_uci_bogota = './out_put_files/data_covid_uci_bogota.csv'
name_covid_uci_bogota = 'data_covid_uci_bogota.csv'
out_name_s3_data_covid='data_covid'
output_covid = './out_put_files/data_covid.csv'
name_covid = 'data_covid.csv'
data_ciudades = "https://raw.githubusercontent.com/panchicore/dane_colombia/master/data/ciudades.csv"
out_name_s3_data_ciudades='data_ciudades'
output_data_ciudades = './out_put_files/data_ciudades.csv'
name_ciudades = 'data_ciudades.csv'